#!/usr/bin/env bash

# link .bash_style to ~/.bash_style

file=".bash_style"
source_file="$PWD/$file"
target_file="$HOME/$file"

echo "Run: ln -s \"$source_file\" \"$target_file\""
read -rp "Continue symlink? [y/N]: " reply

case $reply in
[Yy]*) ln -vs "$source_file" "$target_file" ;;
*) exit 1 ;;
esac
